### ISSUE TITLE
Refactoring (global namespace pollution)

### ISSUE THREAD

**Issue by kilojapan** [mil-tokyo/tempura#8]
"""
var nodejs = ...
if (nodejs) {
 ...
}

$M = AgentSmith.Matrix
"""
||
V
"""
(function(nodejs, $M) {
  if (nodejs) {
   ...
  }
 ...
})(typeof window === 'undefined', AgentSmith.Matrix)
"""
something like this

**Comment by kilojapan** [comment]
@yuichiroTCY 
@akanehira 
@tetsumano 
 List fixed functions to refactor

**Comment by akanehira** [comment]
k-means, GMM, CCA, PCA are fixed

**Comment by akanehira** [comment]
regressions are fixed
